id: I338D9B6D
legacy_id: P009139
ocr_import_info:
  bdrc_scan_id: W1KG9453
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T10:40:30'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T18:32:36.014142+00:00'
last_modified: 2022-09-01 02:32:50.298652
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG9453
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG9453
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཞེ་ཆེན་ཆོས་འབྱུང་། ༼དབུ་ཆེན་བྲིས་མ།༽
  author: ཞེ་ཆེན་རྒྱལ་ཚབ ༠༤་འགྱུར་མེད་པདྨ་རྣམ་རྒྱལ།
statistics:
  ocr_word_mean_confidence_index: 0.856209524053962
  ocr_word_median_confidence_index: 0.9399999976158142
quality: null
bases:
  I1KG9468:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9468
      total_pages: 596
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9468.txt
    statistics:
      ocr_word_median_confidence_index: 0.9399999976158142
      ocr_word_mean_confidence_index: 0.856209524053962
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
