id: I338D9B6D
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T10:44:05+00:00'
last_modified: '2022-06-08T08:54:01.399748+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9453
  title: ཞེ་ཆེན་ཆོས་འབྱུང་། ༼དབུ་ཆེན་བྲིས་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BFAA:
      image_group_id: I1KG9468
      title: ''
      total_pages: 596
      order: 1
      base_file: BFAA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
