id: P009139
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:24:53.592673
source_metadata:
  id: bdr:W1KG9453
  title: ཞེ་ཆེན་ཆོས་འབྱུང་། ༼དབུ་ཆེན་བྲིས་མ།༽
  author: ''
  volumes:
    121ffda6206e41868fdfd0dbe3f07fa9:
      image_group_id: I1KG9468
      title: ''
      volume_number: 1
      total_pages: 596
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
